### ISSUE TITLE
Cannot build 1.1.0 on OS X

### ISSUE THREAD

**Issue by ruipacheco** [cppformat/cppformat#133]
I'm working on the latest OS X with clang version:

```
$ clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```

cppformat 1.0 works fine but when I upgraded to 1.1.0 I get the following error:

```
Undefined symbols for architecture x86_64:
  "fmt::BasicFormatter<char>::format(fmt::BasicStringRef<char>, fmt::ArgList const&)", referenced from:
      fmt::BasicWriter<char>::write(fmt::BasicStringRef<char>, fmt::ArgList) in libshoguncore.a(Daemon.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by vitaut** [comment]
The function is defined [here](https://github.com/cppformat/cppformat/blob/1.1.0/format.cc#L1056) and explicitly instantiated [here](https://github.com/cppformat/cppformat/blob/1.1.0/format.cc#L1129) if `FMT_HEADER_ONLY` macro is not defined. Please check that `FMT_HEADER_ONLY` macro is used consistently in the project. It should be either defined or undefined everywhere. Note that the macro can be defined by a third-party library like spdlog.

**Comment by vitaut** [comment]
@ruipacheco Have you found out if the link error is indeed caused by inconsistent use of `FMT_HEADER_ONLY`? If not could you please post an example to reproduce the error?

**Comment by ruipacheco** [comment]
Yes it is. I added the macro and everything went away.

**Comment by vitaut** [comment]
Thanks for the confirmation. Closing the issue now.

**Comment by MikeMitterer** [comment]
Had the same issue.

I someone else finds this post - here is my solution:

My FindFmt.cmake
```cmake
# - Try to find fmt source lib
#
# Once done this will define
#  fmt_FOUND - System has args
#  fmt_INCLUDE_DIRS - The args include directories

find_package(PkgConfig)

find_file(fmt_INCLUDE_DIR format.h
        PATH fmt
        HINTS fmt
        )

include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set LIBXML2_FOUND to TRUE
# if all listed variables are TRUE
find_package_handle_standard_args(fmt DEFAULT_MSG
        fmt_INCLUDE_DIR
        )

mark_as_advanced(fmt_INCLUDE_DIR)

# Avoids "Undefined symbols for architecture" Error
add_definitions(-DFMT_HEADER_ONLY)

set(fmt_INCLUDE_DIRS ${fmt_INCLUDE_DIR} )

include_directories(${fmt_INCLUDE_DIR})
```

Then in CMakeLists.txt
```cmake
find_package(fmt)
```
Thats it!
